GioF71/squeezelite-docker

README.md

Add support for presets.
Add support for more environment variables.
Still using buster for latest and stable images,

Upgrade to 2022-01-19

---

README.md
RELEASE.md
app/assets/builtin-presets.conf

Add preset `pi-headphones`|Add preset for Raspberry Pi Headphone out
Doc update|Small corrections/typos

Release 2022-03-19

---

README.md
RELEASE.md

Asus Tinkerboard support information provided.
Documentation and release history updated.

Release 2022-04-01

---

README.md

Documentation changes were missing

24 is there any way to send other command line options

---

.github/workflows/docker-multi-arch.yml
README.md
RELEASE.md
build.sh

Fixed #28, bumped images as well

fixed issue #28

---

.github/workflows/docker-multi-arch.yml

Fixed wrong image name for bullseye

fixed bullseye image name

---

.github/workflows/docker-multi-arch.yml

32 squeezelite version mapping

---

.github/workflows/docker-multi-arch.yml

Effectively using versions from dictionary

more progress

---

.github/workflows/docker-multi-arch.yml

31 avoid reference to base images with dates

---

RELEASE.md

add release documentation

---

README.md
RELEASE.md

updated documentation

---

README.md
RELEASE.md
pulse/squeezelite-docker-pulse.service

- Documentation: Fixed typo on PGID notes
- Documentation: Mentioned PulseAudio early in Why section
- PulseAudio/SystemD: Removed my custom player name from unit, now the player name reflects the hostname
- PulseAudio/SystemD: Service now should wait for the network

67 release 2022 09 17

---

README.md

- clarification on volume mounting for PulseAudio mode.

pulseaudio volume mount instruction hopefully clear now

---

.github/workflows/docker-multi-arch.yml
.github/workflows/sync-readme.yml

- Merging build process changes to devel branch

83 review build process

---

README.md
RELEASE.md
app/assets/builtin-presets.conf

88 some new presets

---

.github/workflows/docker-multi-arch.yml
.github/workflows/sync-readme.yml
RELEASE.md

- Build: Only from tags (reduce number of builds)
- Build: Build from main and devel branch only (no dates, no timestamps)

90 only build from tags

---

.github/workflows/docker-multi-arch.yml
.github/workflows/sync-readme.yml
README.md
RELEASE.md
app/assets/builtin-presets.conf

- Bring latest changes to main

Latest updates

---

.github/workflows/docker-multi-arch.yml
RELEASE.md

- support for multiple type of tags

90 only build from tags follow up

---

README.md
RELEASE.md
app/assets/builtin-presets.conf

- Preset for Gustard U12 DDC (x20)

94 preset for gustard u12

---

RELEASE.md

- Bring contents of release 2022-09-28.1 to main

Changes for release 2022-09-28.1

---

Dockerfile
RELEASE.md
app/conf/01-apt-proxy
build.sh
doc/build.md

Add proxy support to devel branch

proxy support complete

---

.github/workflows/docker-multi-arch.yml
Dockerfile
README.md
RELEASE.md
app/bin/run-squeezelite-alsa.sh
app/bin/run-squeezelite-pulse.sh
install/installer.sh

- Add squeezelite-pulseaudio binaries
- Documentation updated
- Dropped the buster build without sourceforge (does not include squeezelite-pulseaudio package)

101 stuttering when changing audio volume on the actual machine

---

RELEASE.md

Release 2022-10-02

---

RELEASE.md

Align with new release contents

---

Dockerfile
README.md
app/bin/run-squeezelite-alsa.sh
doc/config-changes.md
doc/example-alsa-user-mode.md
doc/release.md

Also, in order to contain the size of README.md to the docker hub limits, the documentation has been slightly reviewed

[Feature] Support running in user mode also for alsa output

---

.github/workflows/docker-multi-arch-regular.yml
.github/workflows/docker-multi-arch-sourceforge.yml
README.md
doc/release.md

[Maintenance] GitHub workflow for sourceforge build #183

---

Dockerfile
README.md
app/bin/run-squeezelite-alsa.sh
app/bin/run-squeezelite-pulse.sh
doc/release.md

We can now select custom binaries

181 allow selection of custom binary

---

README.md
app/bin/cmd-line-builder.sh
build.sh
doc/release.md

We can now use spaces in name and model

[Feature] Allow spaces in names #202

---

install/installer.sh

No need for another release though

Clean R2 build (remove unnecessary directory)

---

doc/release.md
install/install-dep.sh

- Removed explicit installation of libasound2

Fix r2 build
